applicationName: "inventory"
deployment:
  podLabels:
    app: inventory
  image:
    repository: docker.release.stakater.com:443/stakater/inventory
    tag: v0.0.1
  imagePullSecrets: "docker-registry-nexus-secret"
rbac:
  create: false
  serviceAccount:
    name: default
configMap: {}
